/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RightComponent: typeof import('./src/components/RightComponent.vue')['default']
    VAppBarComp: typeof import('./src/components/VAppBarComp.vue')['default']
  }
}
