/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartComponent: typeof import('./src/components/CartComponent.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    copy: typeof import('./src/components/FilterComponent copy.vue')['default']
    FilterComponent: typeof import('./src/components/FilterComponent.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RightComponent: typeof import('./src/components/RightComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAppBarComp: typeof import('./src/components/VAppBarComp.vue')['default']
  }
}
