/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    copy: typeof import('./src/components/CategoryCard copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VAppBar: typeof import('./src/components/VAppBar.vue')['default']
    VAppBarComp: typeof import('./src/components/VAppBarComp.vue')['default']
  }
}
