import { defineStore, storeToRefs } from "pinia";
import { computed, ref } from "vue";
import { useCategoryStore } from "./categoryStore";

type ProductDto = {
    id: number
    url: string
    categoryName: string
    displayName: string
    name: string
    merchantName: string
    brandName: string
    price: string
    productRate: number
    stockCount: number
    rate: number
}
export const useProductStore = defineStore("productStore", () => {
  const productList = ref<ProductDto[]>([
    {
      id: 23,
      url: "",
      categoryName: "Elektrik",
      displayName: "POWER KABLO 1.5M",
      name: "POWER KABLO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "300₺",
      productRate: 4,
      stockCount: 4,
      rate: 4,
    },
    {
      id: 24,
      url: "",
      categoryName: "Elektrik",
      displayName: "9 VERİ TRANSFER 3MT AK-610106-030-E",
      name: "9 VERİ TRANSFER 3MT AK-610106-030-E",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 5,
      stockCount: 42,
      rate: 3,
    },
    {
      id: 25,
      url: "",
      categoryName: "Elektrik",
      displayName: "3 METRE HDMI KABLO",
      name: "3 METRE HDMI KABLO",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "450₺",
      productRate: 2,
      stockCount: 200,
      rate: 0,
    },
    {
      id: 26,
      url: "",
      categoryName: "Elektrik",
      displayName: "KLAVYE & MOUSE KABLOSUZ SET SİYAH",
      name: "KLAVYE & MOUSE",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "600₺",
      productRate: 3,
      stockCount: 1,
      rate: 3,
    },
    {
      id: 27,
      url: "",
      categoryName: "Elektrik",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "10₺",
      productRate: 4,
      stockCount: 67,
      rate: 4,
    },
    {
      id: 28,
      url: "",
      categoryName: "Elektrik",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 3,
    },
    {
      id: 29,
      url: "",
      categoryName: "Süpermarket",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 3.5,
    },
    {
      id: 30,
      url: "",
      categoryName: "Süpermarket",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 0,
    },
    {
      id: 31,
      url: "",
      categoryName: "Süpermarket",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 1.5,
    },
    {
      id: 32,
      url: "",
      categoryName: "Süpermarket",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 33,
      url: "",
      categoryName: "Süpermarket",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 34,
      url: "",
      categoryName: "Süpermarket",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 35,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "10₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 36,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 37,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 38,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 2,
    },
    {
      id: 39,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 40,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 41,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 42,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 43,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 44,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 45,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 2,
    },
    {
      id: 46,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 47,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 48,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 49,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 50,
      url: "",
      categoryName: "Moda",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 4,
    },
    {
      id: 51,
      url: "",
      categoryName: "Moda",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 52,
      url: "",
      categoryName: "Moda",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 9,
    },
    {
      id: 53,
      url: "",
      categoryName: "Moda",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 54,
      url: "",
      categoryName: "Moda",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 5,
    },
    {
      id: 55,
      url: "",
      categoryName: "Moda",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 56,
      url: "",
      categoryName: "Moda",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 3,
    },
    {
      id: 57,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 1,
    },
    {
      id: 58,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 59,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 4,
    },
    {
      id: 60,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 61,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 3,
    },
    {
      id: 62,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 63,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 64,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 7,
    },
    {
      id: 65,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 66,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 67,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 1,
    },
    {
      id: 68,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 69,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 5,
    },
    {
      id: 70,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 71,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 3,
    },
  ]);
  const defaultProductList = ref<ProductDto[]>([
    {
      id: 23,
      url: "",
      categoryName: "Elektrik",
      displayName: "POWER KABLO 1.5M",
      name: "POWER KABLO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "300₺",
      productRate: 4,
      stockCount: 4,
      rate: 4,
    },
    {
      id: 24,
      url: "",
      categoryName: "Elektrik",
      displayName: "9 VERİ TRANSFER 3MT AK-610106-030-E",
      name: "9 VERİ TRANSFER 3MT AK-610106-030-E",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 5,
      stockCount: 42,
      rate: 3,
    },
    {
      id: 25,
      url: "",
      categoryName: "Elektrik",
      displayName: "3 METRE HDMI KABLO",
      name: "3 METRE HDMI KABLO",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "450₺",
      productRate: 2,
      stockCount: 200,
      rate: 0,
    },
    {
      id: 26,
      url: "",
      categoryName: "Elektrik",
      displayName: "KLAVYE & MOUSE KABLOSUZ SET SİYAH",
      name: "KLAVYE & MOUSE",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "600₺",
      productRate: 3,
      stockCount: 1,
      rate: 3,
    },
    {
      id: 27,
      url: "",
      categoryName: "Elektrik",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "10₺",
      productRate: 4,
      stockCount: 67,
      rate: 4,
    },
    {
      id: 28,
      url: "",
      categoryName: "Elektrik",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 3,
    },
    {
      id: 29,
      url: "",
      categoryName: "Süpermarket",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 3.5,
    },
    {
      id: 30,
      url: "",
      categoryName: "Süpermarket",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 0,
    },
    {
      id: 31,
      url: "",
      categoryName: "Süpermarket",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 1.5,
    },
    {
      id: 32,
      url: "",
      categoryName: "Süpermarket",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 33,
      url: "",
      categoryName: "Süpermarket",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 34,
      url: "",
      categoryName: "Süpermarket",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 35,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "10₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 36,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 37,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 38,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 2,
    },
    {
      id: 39,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 40,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 41,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 42,
      url: "",
      categoryName: "Kişisel Bakım ve Kozmetik",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 43,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 44,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 45,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 2,
    },
    {
      id: 46,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 47,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 48,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 49,
      url: "",
      categoryName: "Kitap, Kırtasiye, Oyuncak",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 50,
      url: "",
      categoryName: "Moda",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 4,
    },
    {
      id: 51,
      url: "",
      categoryName: "Moda",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 52,
      url: "",
      categoryName: "Moda",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 9,
    },
    {
      id: 53,
      url: "",
      categoryName: "Moda",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 54,
      url: "",
      categoryName: "Moda",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 5,
    },
    {
      id: 55,
      url: "",
      categoryName: "Moda",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 56,
      url: "",
      categoryName: "Moda",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 3,
    },
    {
      id: 57,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "1020₺",
      productRate: 5,
      stockCount: 54,
      rate: 1,
    },
    {
      id: 58,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "eraction between c-myc ",
      name: "eracn c-myc LO 1.5M",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "30₺",
      productRate: 4,
      stockCount: 5,
      rate: 2,
    },
    {
      id: 59,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "overnment has not b10106-030-E",
      name: "33324 ent has not ",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "301₺",
      productRate: 5,
      stockCount: 2,
      rate: 4,
    },
    {
      id: 60,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 61,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 3,
    },
    {
      id: 62,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 63,
      url: "",
      categoryName: "Anne Bebek",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 2,
    },
    {
      id: 64,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 7,
    },
    {
      id: 65,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 2,
    },
    {
      id: 66,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 67,
      url: "",
      categoryName: "Oyun, Konsol",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 1,
    },
    {
      id: 68,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "Chomp Munch Mania",
      name: "",
      merchantName: "Holls Impus",
      brandName: "HImp",
      price: "940₺",
      productRate: 2,
      stockCount: 200,
      rate: 2,
    },
    {
      id: 69,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "ays been interested",
      name: "ays brested",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "700₺",
      productRate: 3,
      stockCount: 167,
      rate: 5,
    },
    {
      id: 70,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "AFOX R5 220 1GB",
      name: "AFOX R5 220 1GB",
      merchantName: "Razey Harry",
      brandName: "Razey Harry",
      price: "30₺",
      productRate: 4,
      stockCount: 67,
      rate: 2,
    },
    {
      id: 71,
      url: "",
      categoryName: "Cep Telefonu ve Aksesuarları",
      displayName: "350W  SP400-A POWER SUPPLY",
      name: "350W POWER SUPPLY",
      merchantName: "Lake Koupl",
      brandName: "Looply",
      price: "2020₺",
      productRate: 5,
      stockCount: 54,
      rate: 3,
    },
  ]);
  const selectedProduct = ref<(ProductDto & {quantity: number})[]>([])
  const selectedFavoriteProduct = ref<ProductDto[]>([])

  const rangeSliderValue = ref([] as (number | string)[]);
  const rateValue = ref('' as number | string);
  const productNameValue = ref('' as string);
  const brandNameValue = ref('' as string);
  const isComponentShowToFilter = ref(false)
  const isCartInputIcon = ref(false)

  const maxPrice = computed(() => {
    let count = 0;
    defaultProductList.value.forEach((e) => {
      if (Number(e.price.replace(/₺/g, "")) > count)
        count = Number(e.price.replace(/₺/g, ""));
    });
    return count;
  });

  const minPrice = computed(() => {
    let count = 1000;
    defaultProductList.value.forEach((e) => {
      if (Number(e.price.replace(/₺/g, "")) < count)
        count = Number(e.price.replace(/₺/g, ""));
    });
    return count;
  });

  const resetFilter = async () => {
    rangeSliderValue.value = [minPrice.value, maxPrice.value]
    rateValue.value = ''
    productNameValue.value = ''
    brandNameValue.value = ''
    filterProduct()
  }

  const filterProduct = async () => {
    let allProducts = JSON.parse(JSON.stringify(defaultProductList.value)) as ProductDto[];
    console.log("rangeSliderValue", rangeSliderValue.value);

    const categoryStore = await useCategoryStore();
    const { categoryNameListForFilter } = storeToRefs(categoryStore);
    if (categoryNameListForFilter.value.length) {
      allProducts = allProducts.filter((e) =>
        categoryNameListForFilter.value.includes(e.categoryName)
      );
    }

    if (
      minPrice.value != rangeSliderValue.value[0] &&
      rangeSliderValue.value[0]
    ) {
      allProducts = allProducts.filter(
        e => Number(e.price.replace(/₺/g, "")) >= (rangeSliderValue.value[0] as number)
      );
    }

    if (
      maxPrice.value != rangeSliderValue.value[1] &&
      rangeSliderValue.value[1]
    ) {
      allProducts = allProducts.filter(
        e => Number(e.price.replace(/₺/g, "")) <= (rangeSliderValue.value[1] as number)
      );
    }
    console.log(rateValue.value, rateValue.value === '0')
    if(rateValue.value || rateValue.value === 0) {
        allProducts = allProducts.filter(
            e => e.rate == rateValue.value
        );
    }

    if(productNameValue.value) {
        allProducts = allProducts.filter(
            e => e.displayName.toLocaleLowerCase().includes(productNameValue.value.toLocaleLowerCase())
        );
    }

    if(brandNameValue.value) {
        allProducts = allProducts.filter(
            e => e.brandName.toLocaleLowerCase().includes(brandNameValue.value.toLocaleLowerCase())
        );
    }
        
    productList.value = allProducts;
  };

  const selectProduct = (productId: number) => {
    if(selectedProduct.value.some( e => e.id === productId)) {
        selectedProduct.value = selectedProduct.value.map(e => {
            if(e.id === productId) e.quantity++
            return e
        }) 
    } else selectedProduct.value.push({...productList.value.find( e => e.id === productId) ?? ({} as ProductDto), quantity: 1})
  }
  const selectFavoriteProduct = (productId: number) => {
    if(!selectedFavoriteProduct.value.some( e => e.id === productId)) {
      selectedFavoriteProduct.value.push({...productList.value.find( e => e.id === productId) ?? ({} as ProductDto)})
    }
  }

  return {
    productList,
    defaultProductList,
    rangeSliderValue,
    maxPrice,
    minPrice,
    isComponentShowToFilter,
    rateValue,
    productNameValue,
    brandNameValue,
    selectedProduct,
    selectedFavoriteProduct,
    isCartInputIcon,
    filterProduct,
    resetFilter,
    selectProduct,
    selectFavoriteProduct,
  };
});
